//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportSheet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BlogComment
    {
        public long CommentId { get; set; }
        public long PostId { get; set; }
        public string Message { get; set; }
        public System.DateTime Date { get; set; }
        public string Name { get; set; }
    
        public virtual BlogPost BlogPost { get; set; }
    }
}
