//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportSheet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DownloadHistory
    {
        public long DownloadId { get; set; }
        public string Id { get; set; }
        public System.DateTime DateCreated { get; set; }
        public string Email { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
